/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyEmailTokenRouteImport } from './routes/verify-email.$token'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedCreateOrgRouteImport } from './routes/_protected/create-org'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/_admin'
import { Route as ProtectedOrgsIndexRouteImport } from './routes/_protected/orgs.index'
import { Route as ProtectedOrgsOrgSlugRouteImport } from './routes/_protected/orgs.$orgSlug'
import { Route as ProtectedAdminAdminRouteImport } from './routes/_protected/_admin/admin'
import { Route as ProtectedOrgsOrgSlugIndexRouteImport } from './routes/_protected/orgs.$orgSlug/index'
import { Route as ProtectedOrgsOrgSlugStaffRouteImport } from './routes/_protected/orgs.$orgSlug/staff'
import { Route as ProtectedOrgsOrgSlugSettingsRouteImport } from './routes/_protected/orgs.$orgSlug/settings'
import { Route as ProtectedOrgsOrgSlugSchedulesRouteImport } from './routes/_protected/orgs.$orgSlug/schedules'
import { Route as ProtectedOrgsOrgSlugQualificationsRouteImport } from './routes/_protected/orgs.$orgSlug/qualifications'
import { Route as ProtectedOrgsOrgSlugMembersRouteImport } from './routes/_protected/orgs.$orgSlug/members'
import { Route as ProtectedOrgsOrgSlugFormsRouteImport } from './routes/_protected/orgs.$orgSlug/forms'
import { Route as ProtectedOrgsOrgSlugAvailabilityRouteImport } from './routes/_protected/orgs.$orgSlug/availability'
import { Route as ProtectedOrgsOrgSlugAssetsRouteImport } from './routes/_protected/orgs.$orgSlug/assets'
import { Route as ProtectedAdminAdminUsersRouteImport } from './routes/_protected/_admin/admin_.users'
import { Route as ProtectedAdminAdminOrgsRouteImport } from './routes/_protected/_admin/admin_.orgs'
import { Route as ProtectedOrgsOrgSlugStaffIndexRouteImport } from './routes/_protected/orgs.$orgSlug/staff.index'
import { Route as ProtectedOrgsOrgSlugSchedulesIndexRouteImport } from './routes/_protected/orgs.$orgSlug/schedules.index'
import { Route as ProtectedOrgsOrgSlugQualificationsIndexRouteImport } from './routes/_protected/orgs.$orgSlug/qualifications.index'
import { Route as ProtectedOrgsOrgSlugFormsIndexRouteImport } from './routes/_protected/orgs.$orgSlug/forms/index'
import { Route as ProtectedOrgsOrgSlugAssetsIndexRouteImport } from './routes/_protected/orgs.$orgSlug/assets/index'
import { Route as ProtectedOrgsOrgSlugStaffAuditRouteImport } from './routes/_protected/orgs.$orgSlug/staff.audit'
import { Route as ProtectedOrgsOrgSlugStaffStaffMemberIdRouteImport } from './routes/_protected/orgs.$orgSlug/staff.$staffMemberId'
import { Route as ProtectedOrgsOrgSlugSchedulesRequirementsRouteImport } from './routes/_protected/orgs.$orgSlug/schedules.requirements'
import { Route as ProtectedOrgsOrgSlugSchedulesPlatoonsRouteImport } from './routes/_protected/orgs.$orgSlug/schedules.platoons'
import { Route as ProtectedOrgsOrgSlugSchedulesScheduleIdRouteImport } from './routes/_protected/orgs.$orgSlug/schedules.$scheduleId'
import { Route as ProtectedOrgsOrgSlugFormsSubmissionsRouteImport } from './routes/_protected/orgs.$orgSlug/forms/submissions'
import { Route as ProtectedOrgsOrgSlugAssetsNewRouteImport } from './routes/_protected/orgs.$orgSlug/assets/new'
import { Route as ProtectedOrgsOrgSlugAssetsMyGearRouteImport } from './routes/_protected/orgs.$orgSlug/assets/my-gear'
import { Route as ProtectedOrgsOrgSlugAssetsAssetIdRouteImport } from './routes/_protected/orgs.$orgSlug/assets/$assetId'
import { Route as ProtectedOrgsOrgSlugSchedulesPlatoonsIndexRouteImport } from './routes/_protected/orgs.$orgSlug/schedules.platoons.index'
import { Route as ProtectedOrgsOrgSlugFormsSubmissionsIndexRouteImport } from './routes/_protected/orgs.$orgSlug/forms/submissions/index'
import { Route as ProtectedOrgsOrgSlugSchedulesPlatoonsPlatoonIdRouteImport } from './routes/_protected/orgs.$orgSlug/schedules.platoons.$platoonId'
import { Route as ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRouteImport } from './routes/_protected/orgs.$orgSlug/qualifications.positions.$positionId'
import { Route as ProtectedOrgsOrgSlugFormsTemplatesNewRouteImport } from './routes/_protected/orgs.$orgSlug/forms/templates.new'
import { Route as ProtectedOrgsOrgSlugFormsTemplatesTemplateIdRouteImport } from './routes/_protected/orgs.$orgSlug/forms/templates.$templateId'
import { Route as ProtectedOrgsOrgSlugFormsSubmissionsSubmissionIdRouteImport } from './routes/_protected/orgs.$orgSlug/forms/submissions/$submissionId'
import { Route as ProtectedOrgsOrgSlugFormsFillTemplateIdRouteImport } from './routes/_protected/orgs.$orgSlug/forms/fill.$templateId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailTokenRoute = VerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCreateOrgRoute = ProtectedCreateOrgRouteImport.update({
  id: '/create-org',
  path: '/create-org',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrgsIndexRoute = ProtectedOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrgsOrgSlugRoute = ProtectedOrgsOrgSlugRouteImport.update({
  id: '/orgs/$orgSlug',
  path: '/orgs/$orgSlug',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminAdminRoute = ProtectedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedOrgsOrgSlugIndexRoute =
  ProtectedOrgsOrgSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedOrgsOrgSlugStaffRoute =
  ProtectedOrgsOrgSlugStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedOrgsOrgSlugSettingsRoute =
  ProtectedOrgsOrgSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedOrgsOrgSlugSchedulesRoute =
  ProtectedOrgsOrgSlugSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedOrgsOrgSlugQualificationsRoute =
  ProtectedOrgsOrgSlugQualificationsRouteImport.update({
    id: '/qualifications',
    path: '/qualifications',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedOrgsOrgSlugMembersRoute =
  ProtectedOrgsOrgSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedOrgsOrgSlugFormsRoute =
  ProtectedOrgsOrgSlugFormsRouteImport.update({
    id: '/forms',
    path: '/forms',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedOrgsOrgSlugAvailabilityRoute =
  ProtectedOrgsOrgSlugAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedOrgsOrgSlugAssetsRoute =
  ProtectedOrgsOrgSlugAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedAdminAdminUsersRoute =
  ProtectedAdminAdminUsersRouteImport.update({
    id: '/admin_/users',
    path: '/admin/users',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminAdminOrgsRoute = ProtectedAdminAdminOrgsRouteImport.update({
  id: '/admin_/orgs',
  path: '/admin/orgs',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedOrgsOrgSlugStaffIndexRoute =
  ProtectedOrgsOrgSlugStaffIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrgsOrgSlugStaffRoute,
  } as any)
const ProtectedOrgsOrgSlugSchedulesIndexRoute =
  ProtectedOrgsOrgSlugSchedulesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrgsOrgSlugSchedulesRoute,
  } as any)
const ProtectedOrgsOrgSlugQualificationsIndexRoute =
  ProtectedOrgsOrgSlugQualificationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrgsOrgSlugQualificationsRoute,
  } as any)
const ProtectedOrgsOrgSlugFormsIndexRoute =
  ProtectedOrgsOrgSlugFormsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrgsOrgSlugFormsRoute,
  } as any)
const ProtectedOrgsOrgSlugAssetsIndexRoute =
  ProtectedOrgsOrgSlugAssetsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrgsOrgSlugAssetsRoute,
  } as any)
const ProtectedOrgsOrgSlugStaffAuditRoute =
  ProtectedOrgsOrgSlugStaffAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => ProtectedOrgsOrgSlugStaffRoute,
  } as any)
const ProtectedOrgsOrgSlugStaffStaffMemberIdRoute =
  ProtectedOrgsOrgSlugStaffStaffMemberIdRouteImport.update({
    id: '/$staffMemberId',
    path: '/$staffMemberId',
    getParentRoute: () => ProtectedOrgsOrgSlugStaffRoute,
  } as any)
const ProtectedOrgsOrgSlugSchedulesRequirementsRoute =
  ProtectedOrgsOrgSlugSchedulesRequirementsRouteImport.update({
    id: '/requirements',
    path: '/requirements',
    getParentRoute: () => ProtectedOrgsOrgSlugSchedulesRoute,
  } as any)
const ProtectedOrgsOrgSlugSchedulesPlatoonsRoute =
  ProtectedOrgsOrgSlugSchedulesPlatoonsRouteImport.update({
    id: '/platoons',
    path: '/platoons',
    getParentRoute: () => ProtectedOrgsOrgSlugSchedulesRoute,
  } as any)
const ProtectedOrgsOrgSlugSchedulesScheduleIdRoute =
  ProtectedOrgsOrgSlugSchedulesScheduleIdRouteImport.update({
    id: '/$scheduleId',
    path: '/$scheduleId',
    getParentRoute: () => ProtectedOrgsOrgSlugSchedulesRoute,
  } as any)
const ProtectedOrgsOrgSlugFormsSubmissionsRoute =
  ProtectedOrgsOrgSlugFormsSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => ProtectedOrgsOrgSlugFormsRoute,
  } as any)
const ProtectedOrgsOrgSlugAssetsNewRoute =
  ProtectedOrgsOrgSlugAssetsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ProtectedOrgsOrgSlugAssetsRoute,
  } as any)
const ProtectedOrgsOrgSlugAssetsMyGearRoute =
  ProtectedOrgsOrgSlugAssetsMyGearRouteImport.update({
    id: '/my-gear',
    path: '/my-gear',
    getParentRoute: () => ProtectedOrgsOrgSlugAssetsRoute,
  } as any)
const ProtectedOrgsOrgSlugAssetsAssetIdRoute =
  ProtectedOrgsOrgSlugAssetsAssetIdRouteImport.update({
    id: '/$assetId',
    path: '/$assetId',
    getParentRoute: () => ProtectedOrgsOrgSlugAssetsRoute,
  } as any)
const ProtectedOrgsOrgSlugSchedulesPlatoonsIndexRoute =
  ProtectedOrgsOrgSlugSchedulesPlatoonsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrgsOrgSlugSchedulesPlatoonsRoute,
  } as any)
const ProtectedOrgsOrgSlugFormsSubmissionsIndexRoute =
  ProtectedOrgsOrgSlugFormsSubmissionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrgsOrgSlugFormsSubmissionsRoute,
  } as any)
const ProtectedOrgsOrgSlugSchedulesPlatoonsPlatoonIdRoute =
  ProtectedOrgsOrgSlugSchedulesPlatoonsPlatoonIdRouteImport.update({
    id: '/$platoonId',
    path: '/$platoonId',
    getParentRoute: () => ProtectedOrgsOrgSlugSchedulesPlatoonsRoute,
  } as any)
const ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRoute =
  ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRouteImport.update({
    id: '/positions/$positionId',
    path: '/positions/$positionId',
    getParentRoute: () => ProtectedOrgsOrgSlugQualificationsRoute,
  } as any)
const ProtectedOrgsOrgSlugFormsTemplatesNewRoute =
  ProtectedOrgsOrgSlugFormsTemplatesNewRouteImport.update({
    id: '/templates/new',
    path: '/templates/new',
    getParentRoute: () => ProtectedOrgsOrgSlugFormsRoute,
  } as any)
const ProtectedOrgsOrgSlugFormsTemplatesTemplateIdRoute =
  ProtectedOrgsOrgSlugFormsTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => ProtectedOrgsOrgSlugFormsRoute,
  } as any)
const ProtectedOrgsOrgSlugFormsSubmissionsSubmissionIdRoute =
  ProtectedOrgsOrgSlugFormsSubmissionsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => ProtectedOrgsOrgSlugFormsSubmissionsRoute,
  } as any)
const ProtectedOrgsOrgSlugFormsFillTemplateIdRoute =
  ProtectedOrgsOrgSlugFormsFillTemplateIdRouteImport.update({
    id: '/fill/$templateId',
    path: '/fill/$templateId',
    getParentRoute: () => ProtectedOrgsOrgSlugFormsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/create-org': typeof ProtectedCreateOrgRoute
  '/profile': typeof ProtectedProfileRoute
  '/join/$token': typeof JoinTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/admin': typeof ProtectedAdminAdminRoute
  '/orgs/$orgSlug': typeof ProtectedOrgsOrgSlugRouteWithChildren
  '/orgs/': typeof ProtectedOrgsIndexRoute
  '/admin/orgs': typeof ProtectedAdminAdminOrgsRoute
  '/admin/users': typeof ProtectedAdminAdminUsersRoute
  '/orgs/$orgSlug/assets': typeof ProtectedOrgsOrgSlugAssetsRouteWithChildren
  '/orgs/$orgSlug/availability': typeof ProtectedOrgsOrgSlugAvailabilityRoute
  '/orgs/$orgSlug/forms': typeof ProtectedOrgsOrgSlugFormsRouteWithChildren
  '/orgs/$orgSlug/members': typeof ProtectedOrgsOrgSlugMembersRoute
  '/orgs/$orgSlug/qualifications': typeof ProtectedOrgsOrgSlugQualificationsRouteWithChildren
  '/orgs/$orgSlug/schedules': typeof ProtectedOrgsOrgSlugSchedulesRouteWithChildren
  '/orgs/$orgSlug/settings': typeof ProtectedOrgsOrgSlugSettingsRoute
  '/orgs/$orgSlug/staff': typeof ProtectedOrgsOrgSlugStaffRouteWithChildren
  '/orgs/$orgSlug/': typeof ProtectedOrgsOrgSlugIndexRoute
  '/orgs/$orgSlug/assets/$assetId': typeof ProtectedOrgsOrgSlugAssetsAssetIdRoute
  '/orgs/$orgSlug/assets/my-gear': typeof ProtectedOrgsOrgSlugAssetsMyGearRoute
  '/orgs/$orgSlug/assets/new': typeof ProtectedOrgsOrgSlugAssetsNewRoute
  '/orgs/$orgSlug/forms/submissions': typeof ProtectedOrgsOrgSlugFormsSubmissionsRouteWithChildren
  '/orgs/$orgSlug/schedules/$scheduleId': typeof ProtectedOrgsOrgSlugSchedulesScheduleIdRoute
  '/orgs/$orgSlug/schedules/platoons': typeof ProtectedOrgsOrgSlugSchedulesPlatoonsRouteWithChildren
  '/orgs/$orgSlug/schedules/requirements': typeof ProtectedOrgsOrgSlugSchedulesRequirementsRoute
  '/orgs/$orgSlug/staff/$staffMemberId': typeof ProtectedOrgsOrgSlugStaffStaffMemberIdRoute
  '/orgs/$orgSlug/staff/audit': typeof ProtectedOrgsOrgSlugStaffAuditRoute
  '/orgs/$orgSlug/assets/': typeof ProtectedOrgsOrgSlugAssetsIndexRoute
  '/orgs/$orgSlug/forms/': typeof ProtectedOrgsOrgSlugFormsIndexRoute
  '/orgs/$orgSlug/qualifications/': typeof ProtectedOrgsOrgSlugQualificationsIndexRoute
  '/orgs/$orgSlug/schedules/': typeof ProtectedOrgsOrgSlugSchedulesIndexRoute
  '/orgs/$orgSlug/staff/': typeof ProtectedOrgsOrgSlugStaffIndexRoute
  '/orgs/$orgSlug/forms/fill/$templateId': typeof ProtectedOrgsOrgSlugFormsFillTemplateIdRoute
  '/orgs/$orgSlug/forms/submissions/$submissionId': typeof ProtectedOrgsOrgSlugFormsSubmissionsSubmissionIdRoute
  '/orgs/$orgSlug/forms/templates/$templateId': typeof ProtectedOrgsOrgSlugFormsTemplatesTemplateIdRoute
  '/orgs/$orgSlug/forms/templates/new': typeof ProtectedOrgsOrgSlugFormsTemplatesNewRoute
  '/orgs/$orgSlug/qualifications/positions/$positionId': typeof ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRoute
  '/orgs/$orgSlug/schedules/platoons/$platoonId': typeof ProtectedOrgsOrgSlugSchedulesPlatoonsPlatoonIdRoute
  '/orgs/$orgSlug/forms/submissions/': typeof ProtectedOrgsOrgSlugFormsSubmissionsIndexRoute
  '/orgs/$orgSlug/schedules/platoons/': typeof ProtectedOrgsOrgSlugSchedulesPlatoonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/create-org': typeof ProtectedCreateOrgRoute
  '/profile': typeof ProtectedProfileRoute
  '/join/$token': typeof JoinTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/admin': typeof ProtectedAdminAdminRoute
  '/orgs': typeof ProtectedOrgsIndexRoute
  '/admin/orgs': typeof ProtectedAdminAdminOrgsRoute
  '/admin/users': typeof ProtectedAdminAdminUsersRoute
  '/orgs/$orgSlug/availability': typeof ProtectedOrgsOrgSlugAvailabilityRoute
  '/orgs/$orgSlug/members': typeof ProtectedOrgsOrgSlugMembersRoute
  '/orgs/$orgSlug/settings': typeof ProtectedOrgsOrgSlugSettingsRoute
  '/orgs/$orgSlug': typeof ProtectedOrgsOrgSlugIndexRoute
  '/orgs/$orgSlug/assets/$assetId': typeof ProtectedOrgsOrgSlugAssetsAssetIdRoute
  '/orgs/$orgSlug/assets/my-gear': typeof ProtectedOrgsOrgSlugAssetsMyGearRoute
  '/orgs/$orgSlug/assets/new': typeof ProtectedOrgsOrgSlugAssetsNewRoute
  '/orgs/$orgSlug/schedules/$scheduleId': typeof ProtectedOrgsOrgSlugSchedulesScheduleIdRoute
  '/orgs/$orgSlug/schedules/requirements': typeof ProtectedOrgsOrgSlugSchedulesRequirementsRoute
  '/orgs/$orgSlug/staff/$staffMemberId': typeof ProtectedOrgsOrgSlugStaffStaffMemberIdRoute
  '/orgs/$orgSlug/staff/audit': typeof ProtectedOrgsOrgSlugStaffAuditRoute
  '/orgs/$orgSlug/assets': typeof ProtectedOrgsOrgSlugAssetsIndexRoute
  '/orgs/$orgSlug/forms': typeof ProtectedOrgsOrgSlugFormsIndexRoute
  '/orgs/$orgSlug/qualifications': typeof ProtectedOrgsOrgSlugQualificationsIndexRoute
  '/orgs/$orgSlug/schedules': typeof ProtectedOrgsOrgSlugSchedulesIndexRoute
  '/orgs/$orgSlug/staff': typeof ProtectedOrgsOrgSlugStaffIndexRoute
  '/orgs/$orgSlug/forms/fill/$templateId': typeof ProtectedOrgsOrgSlugFormsFillTemplateIdRoute
  '/orgs/$orgSlug/forms/submissions/$submissionId': typeof ProtectedOrgsOrgSlugFormsSubmissionsSubmissionIdRoute
  '/orgs/$orgSlug/forms/templates/$templateId': typeof ProtectedOrgsOrgSlugFormsTemplatesTemplateIdRoute
  '/orgs/$orgSlug/forms/templates/new': typeof ProtectedOrgsOrgSlugFormsTemplatesNewRoute
  '/orgs/$orgSlug/qualifications/positions/$positionId': typeof ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRoute
  '/orgs/$orgSlug/schedules/platoons/$platoonId': typeof ProtectedOrgsOrgSlugSchedulesPlatoonsPlatoonIdRoute
  '/orgs/$orgSlug/forms/submissions': typeof ProtectedOrgsOrgSlugFormsSubmissionsIndexRoute
  '/orgs/$orgSlug/schedules/platoons': typeof ProtectedOrgsOrgSlugSchedulesPlatoonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_protected/_admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/create-org': typeof ProtectedCreateOrgRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/join/$token': typeof JoinTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/_protected/_admin/admin': typeof ProtectedAdminAdminRoute
  '/_protected/orgs/$orgSlug': typeof ProtectedOrgsOrgSlugRouteWithChildren
  '/_protected/orgs/': typeof ProtectedOrgsIndexRoute
  '/_protected/_admin/admin_/orgs': typeof ProtectedAdminAdminOrgsRoute
  '/_protected/_admin/admin_/users': typeof ProtectedAdminAdminUsersRoute
  '/_protected/orgs/$orgSlug/assets': typeof ProtectedOrgsOrgSlugAssetsRouteWithChildren
  '/_protected/orgs/$orgSlug/availability': typeof ProtectedOrgsOrgSlugAvailabilityRoute
  '/_protected/orgs/$orgSlug/forms': typeof ProtectedOrgsOrgSlugFormsRouteWithChildren
  '/_protected/orgs/$orgSlug/members': typeof ProtectedOrgsOrgSlugMembersRoute
  '/_protected/orgs/$orgSlug/qualifications': typeof ProtectedOrgsOrgSlugQualificationsRouteWithChildren
  '/_protected/orgs/$orgSlug/schedules': typeof ProtectedOrgsOrgSlugSchedulesRouteWithChildren
  '/_protected/orgs/$orgSlug/settings': typeof ProtectedOrgsOrgSlugSettingsRoute
  '/_protected/orgs/$orgSlug/staff': typeof ProtectedOrgsOrgSlugStaffRouteWithChildren
  '/_protected/orgs/$orgSlug/': typeof ProtectedOrgsOrgSlugIndexRoute
  '/_protected/orgs/$orgSlug/assets/$assetId': typeof ProtectedOrgsOrgSlugAssetsAssetIdRoute
  '/_protected/orgs/$orgSlug/assets/my-gear': typeof ProtectedOrgsOrgSlugAssetsMyGearRoute
  '/_protected/orgs/$orgSlug/assets/new': typeof ProtectedOrgsOrgSlugAssetsNewRoute
  '/_protected/orgs/$orgSlug/forms/submissions': typeof ProtectedOrgsOrgSlugFormsSubmissionsRouteWithChildren
  '/_protected/orgs/$orgSlug/schedules/$scheduleId': typeof ProtectedOrgsOrgSlugSchedulesScheduleIdRoute
  '/_protected/orgs/$orgSlug/schedules/platoons': typeof ProtectedOrgsOrgSlugSchedulesPlatoonsRouteWithChildren
  '/_protected/orgs/$orgSlug/schedules/requirements': typeof ProtectedOrgsOrgSlugSchedulesRequirementsRoute
  '/_protected/orgs/$orgSlug/staff/$staffMemberId': typeof ProtectedOrgsOrgSlugStaffStaffMemberIdRoute
  '/_protected/orgs/$orgSlug/staff/audit': typeof ProtectedOrgsOrgSlugStaffAuditRoute
  '/_protected/orgs/$orgSlug/assets/': typeof ProtectedOrgsOrgSlugAssetsIndexRoute
  '/_protected/orgs/$orgSlug/forms/': typeof ProtectedOrgsOrgSlugFormsIndexRoute
  '/_protected/orgs/$orgSlug/qualifications/': typeof ProtectedOrgsOrgSlugQualificationsIndexRoute
  '/_protected/orgs/$orgSlug/schedules/': typeof ProtectedOrgsOrgSlugSchedulesIndexRoute
  '/_protected/orgs/$orgSlug/staff/': typeof ProtectedOrgsOrgSlugStaffIndexRoute
  '/_protected/orgs/$orgSlug/forms/fill/$templateId': typeof ProtectedOrgsOrgSlugFormsFillTemplateIdRoute
  '/_protected/orgs/$orgSlug/forms/submissions/$submissionId': typeof ProtectedOrgsOrgSlugFormsSubmissionsSubmissionIdRoute
  '/_protected/orgs/$orgSlug/forms/templates/$templateId': typeof ProtectedOrgsOrgSlugFormsTemplatesTemplateIdRoute
  '/_protected/orgs/$orgSlug/forms/templates/new': typeof ProtectedOrgsOrgSlugFormsTemplatesNewRoute
  '/_protected/orgs/$orgSlug/qualifications/positions/$positionId': typeof ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRoute
  '/_protected/orgs/$orgSlug/schedules/platoons/$platoonId': typeof ProtectedOrgsOrgSlugSchedulesPlatoonsPlatoonIdRoute
  '/_protected/orgs/$orgSlug/forms/submissions/': typeof ProtectedOrgsOrgSlugFormsSubmissionsIndexRoute
  '/_protected/orgs/$orgSlug/schedules/platoons/': typeof ProtectedOrgsOrgSlugSchedulesPlatoonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/create-org'
    | '/profile'
    | '/join/$token'
    | '/reset-password/$token'
    | '/verify-email/$token'
    | '/admin'
    | '/orgs/$orgSlug'
    | '/orgs/'
    | '/admin/orgs'
    | '/admin/users'
    | '/orgs/$orgSlug/assets'
    | '/orgs/$orgSlug/availability'
    | '/orgs/$orgSlug/forms'
    | '/orgs/$orgSlug/members'
    | '/orgs/$orgSlug/qualifications'
    | '/orgs/$orgSlug/schedules'
    | '/orgs/$orgSlug/settings'
    | '/orgs/$orgSlug/staff'
    | '/orgs/$orgSlug/'
    | '/orgs/$orgSlug/assets/$assetId'
    | '/orgs/$orgSlug/assets/my-gear'
    | '/orgs/$orgSlug/assets/new'
    | '/orgs/$orgSlug/forms/submissions'
    | '/orgs/$orgSlug/schedules/$scheduleId'
    | '/orgs/$orgSlug/schedules/platoons'
    | '/orgs/$orgSlug/schedules/requirements'
    | '/orgs/$orgSlug/staff/$staffMemberId'
    | '/orgs/$orgSlug/staff/audit'
    | '/orgs/$orgSlug/assets/'
    | '/orgs/$orgSlug/forms/'
    | '/orgs/$orgSlug/qualifications/'
    | '/orgs/$orgSlug/schedules/'
    | '/orgs/$orgSlug/staff/'
    | '/orgs/$orgSlug/forms/fill/$templateId'
    | '/orgs/$orgSlug/forms/submissions/$submissionId'
    | '/orgs/$orgSlug/forms/templates/$templateId'
    | '/orgs/$orgSlug/forms/templates/new'
    | '/orgs/$orgSlug/qualifications/positions/$positionId'
    | '/orgs/$orgSlug/schedules/platoons/$platoonId'
    | '/orgs/$orgSlug/forms/submissions/'
    | '/orgs/$orgSlug/schedules/platoons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/create-org'
    | '/profile'
    | '/join/$token'
    | '/reset-password/$token'
    | '/verify-email/$token'
    | '/admin'
    | '/orgs'
    | '/admin/orgs'
    | '/admin/users'
    | '/orgs/$orgSlug/availability'
    | '/orgs/$orgSlug/members'
    | '/orgs/$orgSlug/settings'
    | '/orgs/$orgSlug'
    | '/orgs/$orgSlug/assets/$assetId'
    | '/orgs/$orgSlug/assets/my-gear'
    | '/orgs/$orgSlug/assets/new'
    | '/orgs/$orgSlug/schedules/$scheduleId'
    | '/orgs/$orgSlug/schedules/requirements'
    | '/orgs/$orgSlug/staff/$staffMemberId'
    | '/orgs/$orgSlug/staff/audit'
    | '/orgs/$orgSlug/assets'
    | '/orgs/$orgSlug/forms'
    | '/orgs/$orgSlug/qualifications'
    | '/orgs/$orgSlug/schedules'
    | '/orgs/$orgSlug/staff'
    | '/orgs/$orgSlug/forms/fill/$templateId'
    | '/orgs/$orgSlug/forms/submissions/$submissionId'
    | '/orgs/$orgSlug/forms/templates/$templateId'
    | '/orgs/$orgSlug/forms/templates/new'
    | '/orgs/$orgSlug/qualifications/positions/$positionId'
    | '/orgs/$orgSlug/schedules/platoons/$platoonId'
    | '/orgs/$orgSlug/forms/submissions'
    | '/orgs/$orgSlug/schedules/platoons'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_protected/_admin'
    | '/_protected/create-org'
    | '/_protected/profile'
    | '/join/$token'
    | '/reset-password/$token'
    | '/verify-email/$token'
    | '/_protected/_admin/admin'
    | '/_protected/orgs/$orgSlug'
    | '/_protected/orgs/'
    | '/_protected/_admin/admin_/orgs'
    | '/_protected/_admin/admin_/users'
    | '/_protected/orgs/$orgSlug/assets'
    | '/_protected/orgs/$orgSlug/availability'
    | '/_protected/orgs/$orgSlug/forms'
    | '/_protected/orgs/$orgSlug/members'
    | '/_protected/orgs/$orgSlug/qualifications'
    | '/_protected/orgs/$orgSlug/schedules'
    | '/_protected/orgs/$orgSlug/settings'
    | '/_protected/orgs/$orgSlug/staff'
    | '/_protected/orgs/$orgSlug/'
    | '/_protected/orgs/$orgSlug/assets/$assetId'
    | '/_protected/orgs/$orgSlug/assets/my-gear'
    | '/_protected/orgs/$orgSlug/assets/new'
    | '/_protected/orgs/$orgSlug/forms/submissions'
    | '/_protected/orgs/$orgSlug/schedules/$scheduleId'
    | '/_protected/orgs/$orgSlug/schedules/platoons'
    | '/_protected/orgs/$orgSlug/schedules/requirements'
    | '/_protected/orgs/$orgSlug/staff/$staffMemberId'
    | '/_protected/orgs/$orgSlug/staff/audit'
    | '/_protected/orgs/$orgSlug/assets/'
    | '/_protected/orgs/$orgSlug/forms/'
    | '/_protected/orgs/$orgSlug/qualifications/'
    | '/_protected/orgs/$orgSlug/schedules/'
    | '/_protected/orgs/$orgSlug/staff/'
    | '/_protected/orgs/$orgSlug/forms/fill/$templateId'
    | '/_protected/orgs/$orgSlug/forms/submissions/$submissionId'
    | '/_protected/orgs/$orgSlug/forms/templates/$templateId'
    | '/_protected/orgs/$orgSlug/forms/templates/new'
    | '/_protected/orgs/$orgSlug/qualifications/positions/$positionId'
    | '/_protected/orgs/$orgSlug/schedules/platoons/$platoonId'
    | '/_protected/orgs/$orgSlug/forms/submissions/'
    | '/_protected/orgs/$orgSlug/schedules/platoons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  VerifyEmailTokenRoute: typeof VerifyEmailTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/$token': {
      id: '/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof VerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/create-org': {
      id: '/_protected/create-org'
      path: '/create-org'
      fullPath: '/create-org'
      preLoaderRoute: typeof ProtectedCreateOrgRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_admin': {
      id: '/_protected/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/orgs/': {
      id: '/_protected/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof ProtectedOrgsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/orgs/$orgSlug': {
      id: '/_protected/orgs/$orgSlug'
      path: '/orgs/$orgSlug'
      fullPath: '/orgs/$orgSlug'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_admin/admin': {
      id: '/_protected/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminAdminRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/orgs/$orgSlug/': {
      id: '/_protected/orgs/$orgSlug/'
      path: '/'
      fullPath: '/orgs/$orgSlug/'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugIndexRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/orgs/$orgSlug/staff': {
      id: '/_protected/orgs/$orgSlug/staff'
      path: '/staff'
      fullPath: '/orgs/$orgSlug/staff'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugStaffRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/orgs/$orgSlug/settings': {
      id: '/_protected/orgs/$orgSlug/settings'
      path: '/settings'
      fullPath: '/orgs/$orgSlug/settings'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugSettingsRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/orgs/$orgSlug/schedules': {
      id: '/_protected/orgs/$orgSlug/schedules'
      path: '/schedules'
      fullPath: '/orgs/$orgSlug/schedules'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugSchedulesRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/orgs/$orgSlug/qualifications': {
      id: '/_protected/orgs/$orgSlug/qualifications'
      path: '/qualifications'
      fullPath: '/orgs/$orgSlug/qualifications'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugQualificationsRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/orgs/$orgSlug/members': {
      id: '/_protected/orgs/$orgSlug/members'
      path: '/members'
      fullPath: '/orgs/$orgSlug/members'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugMembersRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/orgs/$orgSlug/forms': {
      id: '/_protected/orgs/$orgSlug/forms'
      path: '/forms'
      fullPath: '/orgs/$orgSlug/forms'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugFormsRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/orgs/$orgSlug/availability': {
      id: '/_protected/orgs/$orgSlug/availability'
      path: '/availability'
      fullPath: '/orgs/$orgSlug/availability'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugAvailabilityRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/orgs/$orgSlug/assets': {
      id: '/_protected/orgs/$orgSlug/assets'
      path: '/assets'
      fullPath: '/orgs/$orgSlug/assets'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugAssetsRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/_admin/admin_/users': {
      id: '/_protected/_admin/admin_/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof ProtectedAdminAdminUsersRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_admin/admin_/orgs': {
      id: '/_protected/_admin/admin_/orgs'
      path: '/admin/orgs'
      fullPath: '/admin/orgs'
      preLoaderRoute: typeof ProtectedAdminAdminOrgsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/orgs/$orgSlug/staff/': {
      id: '/_protected/orgs/$orgSlug/staff/'
      path: '/'
      fullPath: '/orgs/$orgSlug/staff/'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugStaffIndexRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugStaffRoute
    }
    '/_protected/orgs/$orgSlug/schedules/': {
      id: '/_protected/orgs/$orgSlug/schedules/'
      path: '/'
      fullPath: '/orgs/$orgSlug/schedules/'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugSchedulesIndexRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugSchedulesRoute
    }
    '/_protected/orgs/$orgSlug/qualifications/': {
      id: '/_protected/orgs/$orgSlug/qualifications/'
      path: '/'
      fullPath: '/orgs/$orgSlug/qualifications/'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugQualificationsIndexRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugQualificationsRoute
    }
    '/_protected/orgs/$orgSlug/forms/': {
      id: '/_protected/orgs/$orgSlug/forms/'
      path: '/'
      fullPath: '/orgs/$orgSlug/forms/'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugFormsIndexRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugFormsRoute
    }
    '/_protected/orgs/$orgSlug/assets/': {
      id: '/_protected/orgs/$orgSlug/assets/'
      path: '/'
      fullPath: '/orgs/$orgSlug/assets/'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugAssetsIndexRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugAssetsRoute
    }
    '/_protected/orgs/$orgSlug/staff/audit': {
      id: '/_protected/orgs/$orgSlug/staff/audit'
      path: '/audit'
      fullPath: '/orgs/$orgSlug/staff/audit'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugStaffAuditRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugStaffRoute
    }
    '/_protected/orgs/$orgSlug/staff/$staffMemberId': {
      id: '/_protected/orgs/$orgSlug/staff/$staffMemberId'
      path: '/$staffMemberId'
      fullPath: '/orgs/$orgSlug/staff/$staffMemberId'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugStaffStaffMemberIdRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugStaffRoute
    }
    '/_protected/orgs/$orgSlug/schedules/requirements': {
      id: '/_protected/orgs/$orgSlug/schedules/requirements'
      path: '/requirements'
      fullPath: '/orgs/$orgSlug/schedules/requirements'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugSchedulesRequirementsRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugSchedulesRoute
    }
    '/_protected/orgs/$orgSlug/schedules/platoons': {
      id: '/_protected/orgs/$orgSlug/schedules/platoons'
      path: '/platoons'
      fullPath: '/orgs/$orgSlug/schedules/platoons'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugSchedulesPlatoonsRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugSchedulesRoute
    }
    '/_protected/orgs/$orgSlug/schedules/$scheduleId': {
      id: '/_protected/orgs/$orgSlug/schedules/$scheduleId'
      path: '/$scheduleId'
      fullPath: '/orgs/$orgSlug/schedules/$scheduleId'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugSchedulesScheduleIdRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugSchedulesRoute
    }
    '/_protected/orgs/$orgSlug/forms/submissions': {
      id: '/_protected/orgs/$orgSlug/forms/submissions'
      path: '/submissions'
      fullPath: '/orgs/$orgSlug/forms/submissions'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugFormsSubmissionsRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugFormsRoute
    }
    '/_protected/orgs/$orgSlug/assets/new': {
      id: '/_protected/orgs/$orgSlug/assets/new'
      path: '/new'
      fullPath: '/orgs/$orgSlug/assets/new'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugAssetsNewRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugAssetsRoute
    }
    '/_protected/orgs/$orgSlug/assets/my-gear': {
      id: '/_protected/orgs/$orgSlug/assets/my-gear'
      path: '/my-gear'
      fullPath: '/orgs/$orgSlug/assets/my-gear'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugAssetsMyGearRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugAssetsRoute
    }
    '/_protected/orgs/$orgSlug/assets/$assetId': {
      id: '/_protected/orgs/$orgSlug/assets/$assetId'
      path: '/$assetId'
      fullPath: '/orgs/$orgSlug/assets/$assetId'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugAssetsAssetIdRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugAssetsRoute
    }
    '/_protected/orgs/$orgSlug/schedules/platoons/': {
      id: '/_protected/orgs/$orgSlug/schedules/platoons/'
      path: '/'
      fullPath: '/orgs/$orgSlug/schedules/platoons/'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugSchedulesPlatoonsIndexRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugSchedulesPlatoonsRoute
    }
    '/_protected/orgs/$orgSlug/forms/submissions/': {
      id: '/_protected/orgs/$orgSlug/forms/submissions/'
      path: '/'
      fullPath: '/orgs/$orgSlug/forms/submissions/'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugFormsSubmissionsIndexRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugFormsSubmissionsRoute
    }
    '/_protected/orgs/$orgSlug/schedules/platoons/$platoonId': {
      id: '/_protected/orgs/$orgSlug/schedules/platoons/$platoonId'
      path: '/$platoonId'
      fullPath: '/orgs/$orgSlug/schedules/platoons/$platoonId'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugSchedulesPlatoonsPlatoonIdRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugSchedulesPlatoonsRoute
    }
    '/_protected/orgs/$orgSlug/qualifications/positions/$positionId': {
      id: '/_protected/orgs/$orgSlug/qualifications/positions/$positionId'
      path: '/positions/$positionId'
      fullPath: '/orgs/$orgSlug/qualifications/positions/$positionId'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugQualificationsRoute
    }
    '/_protected/orgs/$orgSlug/forms/templates/new': {
      id: '/_protected/orgs/$orgSlug/forms/templates/new'
      path: '/templates/new'
      fullPath: '/orgs/$orgSlug/forms/templates/new'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugFormsTemplatesNewRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugFormsRoute
    }
    '/_protected/orgs/$orgSlug/forms/templates/$templateId': {
      id: '/_protected/orgs/$orgSlug/forms/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/orgs/$orgSlug/forms/templates/$templateId'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugFormsTemplatesTemplateIdRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugFormsRoute
    }
    '/_protected/orgs/$orgSlug/forms/submissions/$submissionId': {
      id: '/_protected/orgs/$orgSlug/forms/submissions/$submissionId'
      path: '/$submissionId'
      fullPath: '/orgs/$orgSlug/forms/submissions/$submissionId'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugFormsSubmissionsSubmissionIdRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugFormsSubmissionsRoute
    }
    '/_protected/orgs/$orgSlug/forms/fill/$templateId': {
      id: '/_protected/orgs/$orgSlug/forms/fill/$templateId'
      path: '/fill/$templateId'
      fullPath: '/orgs/$orgSlug/forms/fill/$templateId'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugFormsFillTemplateIdRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugFormsRoute
    }
  }
}

interface ProtectedAdminRouteChildren {
  ProtectedAdminAdminRoute: typeof ProtectedAdminAdminRoute
  ProtectedAdminAdminOrgsRoute: typeof ProtectedAdminAdminOrgsRoute
  ProtectedAdminAdminUsersRoute: typeof ProtectedAdminAdminUsersRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminAdminRoute: ProtectedAdminAdminRoute,
  ProtectedAdminAdminOrgsRoute: ProtectedAdminAdminOrgsRoute,
  ProtectedAdminAdminUsersRoute: ProtectedAdminAdminUsersRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedOrgsOrgSlugAssetsRouteChildren {
  ProtectedOrgsOrgSlugAssetsAssetIdRoute: typeof ProtectedOrgsOrgSlugAssetsAssetIdRoute
  ProtectedOrgsOrgSlugAssetsMyGearRoute: typeof ProtectedOrgsOrgSlugAssetsMyGearRoute
  ProtectedOrgsOrgSlugAssetsNewRoute: typeof ProtectedOrgsOrgSlugAssetsNewRoute
  ProtectedOrgsOrgSlugAssetsIndexRoute: typeof ProtectedOrgsOrgSlugAssetsIndexRoute
}

const ProtectedOrgsOrgSlugAssetsRouteChildren: ProtectedOrgsOrgSlugAssetsRouteChildren =
  {
    ProtectedOrgsOrgSlugAssetsAssetIdRoute:
      ProtectedOrgsOrgSlugAssetsAssetIdRoute,
    ProtectedOrgsOrgSlugAssetsMyGearRoute:
      ProtectedOrgsOrgSlugAssetsMyGearRoute,
    ProtectedOrgsOrgSlugAssetsNewRoute: ProtectedOrgsOrgSlugAssetsNewRoute,
    ProtectedOrgsOrgSlugAssetsIndexRoute: ProtectedOrgsOrgSlugAssetsIndexRoute,
  }

const ProtectedOrgsOrgSlugAssetsRouteWithChildren =
  ProtectedOrgsOrgSlugAssetsRoute._addFileChildren(
    ProtectedOrgsOrgSlugAssetsRouteChildren,
  )

interface ProtectedOrgsOrgSlugFormsSubmissionsRouteChildren {
  ProtectedOrgsOrgSlugFormsSubmissionsSubmissionIdRoute: typeof ProtectedOrgsOrgSlugFormsSubmissionsSubmissionIdRoute
  ProtectedOrgsOrgSlugFormsSubmissionsIndexRoute: typeof ProtectedOrgsOrgSlugFormsSubmissionsIndexRoute
}

const ProtectedOrgsOrgSlugFormsSubmissionsRouteChildren: ProtectedOrgsOrgSlugFormsSubmissionsRouteChildren =
  {
    ProtectedOrgsOrgSlugFormsSubmissionsSubmissionIdRoute:
      ProtectedOrgsOrgSlugFormsSubmissionsSubmissionIdRoute,
    ProtectedOrgsOrgSlugFormsSubmissionsIndexRoute:
      ProtectedOrgsOrgSlugFormsSubmissionsIndexRoute,
  }

const ProtectedOrgsOrgSlugFormsSubmissionsRouteWithChildren =
  ProtectedOrgsOrgSlugFormsSubmissionsRoute._addFileChildren(
    ProtectedOrgsOrgSlugFormsSubmissionsRouteChildren,
  )

interface ProtectedOrgsOrgSlugFormsRouteChildren {
  ProtectedOrgsOrgSlugFormsSubmissionsRoute: typeof ProtectedOrgsOrgSlugFormsSubmissionsRouteWithChildren
  ProtectedOrgsOrgSlugFormsIndexRoute: typeof ProtectedOrgsOrgSlugFormsIndexRoute
  ProtectedOrgsOrgSlugFormsFillTemplateIdRoute: typeof ProtectedOrgsOrgSlugFormsFillTemplateIdRoute
  ProtectedOrgsOrgSlugFormsTemplatesTemplateIdRoute: typeof ProtectedOrgsOrgSlugFormsTemplatesTemplateIdRoute
  ProtectedOrgsOrgSlugFormsTemplatesNewRoute: typeof ProtectedOrgsOrgSlugFormsTemplatesNewRoute
}

const ProtectedOrgsOrgSlugFormsRouteChildren: ProtectedOrgsOrgSlugFormsRouteChildren =
  {
    ProtectedOrgsOrgSlugFormsSubmissionsRoute:
      ProtectedOrgsOrgSlugFormsSubmissionsRouteWithChildren,
    ProtectedOrgsOrgSlugFormsIndexRoute: ProtectedOrgsOrgSlugFormsIndexRoute,
    ProtectedOrgsOrgSlugFormsFillTemplateIdRoute:
      ProtectedOrgsOrgSlugFormsFillTemplateIdRoute,
    ProtectedOrgsOrgSlugFormsTemplatesTemplateIdRoute:
      ProtectedOrgsOrgSlugFormsTemplatesTemplateIdRoute,
    ProtectedOrgsOrgSlugFormsTemplatesNewRoute:
      ProtectedOrgsOrgSlugFormsTemplatesNewRoute,
  }

const ProtectedOrgsOrgSlugFormsRouteWithChildren =
  ProtectedOrgsOrgSlugFormsRoute._addFileChildren(
    ProtectedOrgsOrgSlugFormsRouteChildren,
  )

interface ProtectedOrgsOrgSlugQualificationsRouteChildren {
  ProtectedOrgsOrgSlugQualificationsIndexRoute: typeof ProtectedOrgsOrgSlugQualificationsIndexRoute
  ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRoute: typeof ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRoute
}

const ProtectedOrgsOrgSlugQualificationsRouteChildren: ProtectedOrgsOrgSlugQualificationsRouteChildren =
  {
    ProtectedOrgsOrgSlugQualificationsIndexRoute:
      ProtectedOrgsOrgSlugQualificationsIndexRoute,
    ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRoute:
      ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRoute,
  }

const ProtectedOrgsOrgSlugQualificationsRouteWithChildren =
  ProtectedOrgsOrgSlugQualificationsRoute._addFileChildren(
    ProtectedOrgsOrgSlugQualificationsRouteChildren,
  )

interface ProtectedOrgsOrgSlugSchedulesPlatoonsRouteChildren {
  ProtectedOrgsOrgSlugSchedulesPlatoonsPlatoonIdRoute: typeof ProtectedOrgsOrgSlugSchedulesPlatoonsPlatoonIdRoute
  ProtectedOrgsOrgSlugSchedulesPlatoonsIndexRoute: typeof ProtectedOrgsOrgSlugSchedulesPlatoonsIndexRoute
}

const ProtectedOrgsOrgSlugSchedulesPlatoonsRouteChildren: ProtectedOrgsOrgSlugSchedulesPlatoonsRouteChildren =
  {
    ProtectedOrgsOrgSlugSchedulesPlatoonsPlatoonIdRoute:
      ProtectedOrgsOrgSlugSchedulesPlatoonsPlatoonIdRoute,
    ProtectedOrgsOrgSlugSchedulesPlatoonsIndexRoute:
      ProtectedOrgsOrgSlugSchedulesPlatoonsIndexRoute,
  }

const ProtectedOrgsOrgSlugSchedulesPlatoonsRouteWithChildren =
  ProtectedOrgsOrgSlugSchedulesPlatoonsRoute._addFileChildren(
    ProtectedOrgsOrgSlugSchedulesPlatoonsRouteChildren,
  )

interface ProtectedOrgsOrgSlugSchedulesRouteChildren {
  ProtectedOrgsOrgSlugSchedulesScheduleIdRoute: typeof ProtectedOrgsOrgSlugSchedulesScheduleIdRoute
  ProtectedOrgsOrgSlugSchedulesPlatoonsRoute: typeof ProtectedOrgsOrgSlugSchedulesPlatoonsRouteWithChildren
  ProtectedOrgsOrgSlugSchedulesRequirementsRoute: typeof ProtectedOrgsOrgSlugSchedulesRequirementsRoute
  ProtectedOrgsOrgSlugSchedulesIndexRoute: typeof ProtectedOrgsOrgSlugSchedulesIndexRoute
}

const ProtectedOrgsOrgSlugSchedulesRouteChildren: ProtectedOrgsOrgSlugSchedulesRouteChildren =
  {
    ProtectedOrgsOrgSlugSchedulesScheduleIdRoute:
      ProtectedOrgsOrgSlugSchedulesScheduleIdRoute,
    ProtectedOrgsOrgSlugSchedulesPlatoonsRoute:
      ProtectedOrgsOrgSlugSchedulesPlatoonsRouteWithChildren,
    ProtectedOrgsOrgSlugSchedulesRequirementsRoute:
      ProtectedOrgsOrgSlugSchedulesRequirementsRoute,
    ProtectedOrgsOrgSlugSchedulesIndexRoute:
      ProtectedOrgsOrgSlugSchedulesIndexRoute,
  }

const ProtectedOrgsOrgSlugSchedulesRouteWithChildren =
  ProtectedOrgsOrgSlugSchedulesRoute._addFileChildren(
    ProtectedOrgsOrgSlugSchedulesRouteChildren,
  )

interface ProtectedOrgsOrgSlugStaffRouteChildren {
  ProtectedOrgsOrgSlugStaffStaffMemberIdRoute: typeof ProtectedOrgsOrgSlugStaffStaffMemberIdRoute
  ProtectedOrgsOrgSlugStaffAuditRoute: typeof ProtectedOrgsOrgSlugStaffAuditRoute
  ProtectedOrgsOrgSlugStaffIndexRoute: typeof ProtectedOrgsOrgSlugStaffIndexRoute
}

const ProtectedOrgsOrgSlugStaffRouteChildren: ProtectedOrgsOrgSlugStaffRouteChildren =
  {
    ProtectedOrgsOrgSlugStaffStaffMemberIdRoute:
      ProtectedOrgsOrgSlugStaffStaffMemberIdRoute,
    ProtectedOrgsOrgSlugStaffAuditRoute: ProtectedOrgsOrgSlugStaffAuditRoute,
    ProtectedOrgsOrgSlugStaffIndexRoute: ProtectedOrgsOrgSlugStaffIndexRoute,
  }

const ProtectedOrgsOrgSlugStaffRouteWithChildren =
  ProtectedOrgsOrgSlugStaffRoute._addFileChildren(
    ProtectedOrgsOrgSlugStaffRouteChildren,
  )

interface ProtectedOrgsOrgSlugRouteChildren {
  ProtectedOrgsOrgSlugAssetsRoute: typeof ProtectedOrgsOrgSlugAssetsRouteWithChildren
  ProtectedOrgsOrgSlugAvailabilityRoute: typeof ProtectedOrgsOrgSlugAvailabilityRoute
  ProtectedOrgsOrgSlugFormsRoute: typeof ProtectedOrgsOrgSlugFormsRouteWithChildren
  ProtectedOrgsOrgSlugMembersRoute: typeof ProtectedOrgsOrgSlugMembersRoute
  ProtectedOrgsOrgSlugQualificationsRoute: typeof ProtectedOrgsOrgSlugQualificationsRouteWithChildren
  ProtectedOrgsOrgSlugSchedulesRoute: typeof ProtectedOrgsOrgSlugSchedulesRouteWithChildren
  ProtectedOrgsOrgSlugSettingsRoute: typeof ProtectedOrgsOrgSlugSettingsRoute
  ProtectedOrgsOrgSlugStaffRoute: typeof ProtectedOrgsOrgSlugStaffRouteWithChildren
  ProtectedOrgsOrgSlugIndexRoute: typeof ProtectedOrgsOrgSlugIndexRoute
}

const ProtectedOrgsOrgSlugRouteChildren: ProtectedOrgsOrgSlugRouteChildren = {
  ProtectedOrgsOrgSlugAssetsRoute: ProtectedOrgsOrgSlugAssetsRouteWithChildren,
  ProtectedOrgsOrgSlugAvailabilityRoute: ProtectedOrgsOrgSlugAvailabilityRoute,
  ProtectedOrgsOrgSlugFormsRoute: ProtectedOrgsOrgSlugFormsRouteWithChildren,
  ProtectedOrgsOrgSlugMembersRoute: ProtectedOrgsOrgSlugMembersRoute,
  ProtectedOrgsOrgSlugQualificationsRoute:
    ProtectedOrgsOrgSlugQualificationsRouteWithChildren,
  ProtectedOrgsOrgSlugSchedulesRoute:
    ProtectedOrgsOrgSlugSchedulesRouteWithChildren,
  ProtectedOrgsOrgSlugSettingsRoute: ProtectedOrgsOrgSlugSettingsRoute,
  ProtectedOrgsOrgSlugStaffRoute: ProtectedOrgsOrgSlugStaffRouteWithChildren,
  ProtectedOrgsOrgSlugIndexRoute: ProtectedOrgsOrgSlugIndexRoute,
}

const ProtectedOrgsOrgSlugRouteWithChildren =
  ProtectedOrgsOrgSlugRoute._addFileChildren(ProtectedOrgsOrgSlugRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedCreateOrgRoute: typeof ProtectedCreateOrgRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedOrgsOrgSlugRoute: typeof ProtectedOrgsOrgSlugRouteWithChildren
  ProtectedOrgsIndexRoute: typeof ProtectedOrgsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedCreateOrgRoute: ProtectedCreateOrgRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedOrgsOrgSlugRoute: ProtectedOrgsOrgSlugRouteWithChildren,
  ProtectedOrgsIndexRoute: ProtectedOrgsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  JoinTokenRoute: JoinTokenRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  VerifyEmailTokenRoute: VerifyEmailTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
