/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyEmailTokenRouteImport } from './routes/verify-email.$token'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'
import { Route as ProtectedCreateOrgRouteImport } from './routes/_protected/create-org'
import { Route as ProtectedOrgsIndexRouteImport } from './routes/_protected/orgs.index'
import { Route as ProtectedOrgsOrgSlugRouteImport } from './routes/_protected/orgs.$orgSlug'
import { Route as ProtectedOrgsOrgSlugIndexRouteImport } from './routes/_protected/orgs.$orgSlug/index'
import { Route as ProtectedOrgsOrgSlugStaffRouteImport } from './routes/_protected/orgs.$orgSlug/staff'
import { Route as ProtectedOrgsOrgSlugMembersRouteImport } from './routes/_protected/orgs.$orgSlug/members'
import { Route as ProtectedOrgsOrgSlugStaffAuditRouteImport } from './routes/_protected/orgs.$orgSlug/staff.audit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailTokenRoute = VerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCreateOrgRoute = ProtectedCreateOrgRouteImport.update({
  id: '/create-org',
  path: '/create-org',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrgsIndexRoute = ProtectedOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrgsOrgSlugRoute = ProtectedOrgsOrgSlugRouteImport.update({
  id: '/orgs/$orgSlug',
  path: '/orgs/$orgSlug',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrgsOrgSlugIndexRoute =
  ProtectedOrgsOrgSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedOrgsOrgSlugStaffRoute =
  ProtectedOrgsOrgSlugStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedOrgsOrgSlugMembersRoute =
  ProtectedOrgsOrgSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedOrgsOrgSlugStaffAuditRoute =
  ProtectedOrgsOrgSlugStaffAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => ProtectedOrgsOrgSlugStaffRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/create-org': typeof ProtectedCreateOrgRoute
  '/home': typeof ProtectedHomeRoute
  '/profile': typeof ProtectedProfileRoute
  '/join/$token': typeof JoinTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/orgs/$orgSlug': typeof ProtectedOrgsOrgSlugRouteWithChildren
  '/orgs/': typeof ProtectedOrgsIndexRoute
  '/orgs/$orgSlug/members': typeof ProtectedOrgsOrgSlugMembersRoute
  '/orgs/$orgSlug/staff': typeof ProtectedOrgsOrgSlugStaffRouteWithChildren
  '/orgs/$orgSlug/': typeof ProtectedOrgsOrgSlugIndexRoute
  '/orgs/$orgSlug/staff/audit': typeof ProtectedOrgsOrgSlugStaffAuditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/create-org': typeof ProtectedCreateOrgRoute
  '/home': typeof ProtectedHomeRoute
  '/profile': typeof ProtectedProfileRoute
  '/join/$token': typeof JoinTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/orgs': typeof ProtectedOrgsIndexRoute
  '/orgs/$orgSlug/members': typeof ProtectedOrgsOrgSlugMembersRoute
  '/orgs/$orgSlug/staff': typeof ProtectedOrgsOrgSlugStaffRouteWithChildren
  '/orgs/$orgSlug': typeof ProtectedOrgsOrgSlugIndexRoute
  '/orgs/$orgSlug/staff/audit': typeof ProtectedOrgsOrgSlugStaffAuditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_protected/create-org': typeof ProtectedCreateOrgRoute
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/join/$token': typeof JoinTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/_protected/orgs/$orgSlug': typeof ProtectedOrgsOrgSlugRouteWithChildren
  '/_protected/orgs/': typeof ProtectedOrgsIndexRoute
  '/_protected/orgs/$orgSlug/members': typeof ProtectedOrgsOrgSlugMembersRoute
  '/_protected/orgs/$orgSlug/staff': typeof ProtectedOrgsOrgSlugStaffRouteWithChildren
  '/_protected/orgs/$orgSlug/': typeof ProtectedOrgsOrgSlugIndexRoute
  '/_protected/orgs/$orgSlug/staff/audit': typeof ProtectedOrgsOrgSlugStaffAuditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/create-org'
    | '/home'
    | '/profile'
    | '/join/$token'
    | '/reset-password/$token'
    | '/verify-email/$token'
    | '/orgs/$orgSlug'
    | '/orgs/'
    | '/orgs/$orgSlug/members'
    | '/orgs/$orgSlug/staff'
    | '/orgs/$orgSlug/'
    | '/orgs/$orgSlug/staff/audit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/create-org'
    | '/home'
    | '/profile'
    | '/join/$token'
    | '/reset-password/$token'
    | '/verify-email/$token'
    | '/orgs'
    | '/orgs/$orgSlug/members'
    | '/orgs/$orgSlug/staff'
    | '/orgs/$orgSlug'
    | '/orgs/$orgSlug/staff/audit'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_protected/create-org'
    | '/_protected/home'
    | '/_protected/profile'
    | '/join/$token'
    | '/reset-password/$token'
    | '/verify-email/$token'
    | '/_protected/orgs/$orgSlug'
    | '/_protected/orgs/'
    | '/_protected/orgs/$orgSlug/members'
    | '/_protected/orgs/$orgSlug/staff'
    | '/_protected/orgs/$orgSlug/'
    | '/_protected/orgs/$orgSlug/staff/audit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  VerifyEmailTokenRoute: typeof VerifyEmailTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/$token': {
      id: '/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof VerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/create-org': {
      id: '/_protected/create-org'
      path: '/create-org'
      fullPath: '/create-org'
      preLoaderRoute: typeof ProtectedCreateOrgRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/orgs/': {
      id: '/_protected/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof ProtectedOrgsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/orgs/$orgSlug': {
      id: '/_protected/orgs/$orgSlug'
      path: '/orgs/$orgSlug'
      fullPath: '/orgs/$orgSlug'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/orgs/$orgSlug/': {
      id: '/_protected/orgs/$orgSlug/'
      path: '/'
      fullPath: '/orgs/$orgSlug/'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugIndexRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/orgs/$orgSlug/staff': {
      id: '/_protected/orgs/$orgSlug/staff'
      path: '/staff'
      fullPath: '/orgs/$orgSlug/staff'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugStaffRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/orgs/$orgSlug/members': {
      id: '/_protected/orgs/$orgSlug/members'
      path: '/members'
      fullPath: '/orgs/$orgSlug/members'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugMembersRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/orgs/$orgSlug/staff/audit': {
      id: '/_protected/orgs/$orgSlug/staff/audit'
      path: '/audit'
      fullPath: '/orgs/$orgSlug/staff/audit'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugStaffAuditRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugStaffRoute
    }
  }
}

interface ProtectedOrgsOrgSlugStaffRouteChildren {
  ProtectedOrgsOrgSlugStaffAuditRoute: typeof ProtectedOrgsOrgSlugStaffAuditRoute
}

const ProtectedOrgsOrgSlugStaffRouteChildren: ProtectedOrgsOrgSlugStaffRouteChildren =
  {
    ProtectedOrgsOrgSlugStaffAuditRoute: ProtectedOrgsOrgSlugStaffAuditRoute,
  }

const ProtectedOrgsOrgSlugStaffRouteWithChildren =
  ProtectedOrgsOrgSlugStaffRoute._addFileChildren(
    ProtectedOrgsOrgSlugStaffRouteChildren,
  )

interface ProtectedOrgsOrgSlugRouteChildren {
  ProtectedOrgsOrgSlugMembersRoute: typeof ProtectedOrgsOrgSlugMembersRoute
  ProtectedOrgsOrgSlugStaffRoute: typeof ProtectedOrgsOrgSlugStaffRouteWithChildren
  ProtectedOrgsOrgSlugIndexRoute: typeof ProtectedOrgsOrgSlugIndexRoute
}

const ProtectedOrgsOrgSlugRouteChildren: ProtectedOrgsOrgSlugRouteChildren = {
  ProtectedOrgsOrgSlugMembersRoute: ProtectedOrgsOrgSlugMembersRoute,
  ProtectedOrgsOrgSlugStaffRoute: ProtectedOrgsOrgSlugStaffRouteWithChildren,
  ProtectedOrgsOrgSlugIndexRoute: ProtectedOrgsOrgSlugIndexRoute,
}

const ProtectedOrgsOrgSlugRouteWithChildren =
  ProtectedOrgsOrgSlugRoute._addFileChildren(ProtectedOrgsOrgSlugRouteChildren)

interface ProtectedRouteChildren {
  ProtectedCreateOrgRoute: typeof ProtectedCreateOrgRoute
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedOrgsOrgSlugRoute: typeof ProtectedOrgsOrgSlugRouteWithChildren
  ProtectedOrgsIndexRoute: typeof ProtectedOrgsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedCreateOrgRoute: ProtectedCreateOrgRoute,
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedOrgsOrgSlugRoute: ProtectedOrgsOrgSlugRouteWithChildren,
  ProtectedOrgsIndexRoute: ProtectedOrgsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  JoinTokenRoute: JoinTokenRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  VerifyEmailTokenRoute: VerifyEmailTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
