/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyEmailTokenRouteImport } from './routes/verify-email.$token'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'
import { Route as ProtectedCreateOrgRouteImport } from './routes/_protected/create-org'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/_admin'
import { Route as ProtectedOrgsIndexRouteImport } from './routes/_protected/orgs.index'
import { Route as ProtectedOrgsOrgSlugRouteImport } from './routes/_protected/orgs.$orgSlug'
import { Route as ProtectedAdminAdminRouteImport } from './routes/_protected/_admin/admin'
import { Route as ProtectedOrgsOrgSlugIndexRouteImport } from './routes/_protected/orgs.$orgSlug/index'
import { Route as ProtectedOrgsOrgSlugStaffRouteImport } from './routes/_protected/orgs.$orgSlug/staff'
import { Route as ProtectedOrgsOrgSlugSchedulesRouteImport } from './routes/_protected/orgs.$orgSlug/schedules'
import { Route as ProtectedOrgsOrgSlugQualificationsRouteImport } from './routes/_protected/orgs.$orgSlug/qualifications'
import { Route as ProtectedOrgsOrgSlugPlatoonsRouteImport } from './routes/_protected/orgs.$orgSlug/platoons'
import { Route as ProtectedOrgsOrgSlugMembersRouteImport } from './routes/_protected/orgs.$orgSlug/members'
import { Route as ProtectedOrgsOrgSlugAvailabilityRouteImport } from './routes/_protected/orgs.$orgSlug/availability'
import { Route as ProtectedAdminAdminUsersRouteImport } from './routes/_protected/_admin/admin_.users'
import { Route as ProtectedAdminAdminOrgsRouteImport } from './routes/_protected/_admin/admin_.orgs'
import { Route as ProtectedOrgsOrgSlugStaffIndexRouteImport } from './routes/_protected/orgs.$orgSlug/staff.index'
import { Route as ProtectedOrgsOrgSlugSchedulesIndexRouteImport } from './routes/_protected/orgs.$orgSlug/schedules.index'
import { Route as ProtectedOrgsOrgSlugQualificationsIndexRouteImport } from './routes/_protected/orgs.$orgSlug/qualifications.index'
import { Route as ProtectedOrgsOrgSlugPlatoonsIndexRouteImport } from './routes/_protected/orgs.$orgSlug/platoons.index'
import { Route as ProtectedOrgsOrgSlugStaffAuditRouteImport } from './routes/_protected/orgs.$orgSlug/staff.audit'
import { Route as ProtectedOrgsOrgSlugStaffStaffMemberIdRouteImport } from './routes/_protected/orgs.$orgSlug/staff.$staffMemberId'
import { Route as ProtectedOrgsOrgSlugSchedulesScheduleIdRouteImport } from './routes/_protected/orgs.$orgSlug/schedules.$scheduleId'
import { Route as ProtectedOrgsOrgSlugPlatoonsPlatoonIdRouteImport } from './routes/_protected/orgs.$orgSlug/platoons.$platoonId'
import { Route as ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRouteImport } from './routes/_protected/orgs.$orgSlug/qualifications.positions.$positionId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailTokenRoute = VerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCreateOrgRoute = ProtectedCreateOrgRouteImport.update({
  id: '/create-org',
  path: '/create-org',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrgsIndexRoute = ProtectedOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrgsOrgSlugRoute = ProtectedOrgsOrgSlugRouteImport.update({
  id: '/orgs/$orgSlug',
  path: '/orgs/$orgSlug',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminAdminRoute = ProtectedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedOrgsOrgSlugIndexRoute =
  ProtectedOrgsOrgSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedOrgsOrgSlugStaffRoute =
  ProtectedOrgsOrgSlugStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedOrgsOrgSlugSchedulesRoute =
  ProtectedOrgsOrgSlugSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedOrgsOrgSlugQualificationsRoute =
  ProtectedOrgsOrgSlugQualificationsRouteImport.update({
    id: '/qualifications',
    path: '/qualifications',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedOrgsOrgSlugPlatoonsRoute =
  ProtectedOrgsOrgSlugPlatoonsRouteImport.update({
    id: '/platoons',
    path: '/platoons',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedOrgsOrgSlugMembersRoute =
  ProtectedOrgsOrgSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedOrgsOrgSlugAvailabilityRoute =
  ProtectedOrgsOrgSlugAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => ProtectedOrgsOrgSlugRoute,
  } as any)
const ProtectedAdminAdminUsersRoute =
  ProtectedAdminAdminUsersRouteImport.update({
    id: '/admin_/users',
    path: '/admin/users',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminAdminOrgsRoute = ProtectedAdminAdminOrgsRouteImport.update({
  id: '/admin_/orgs',
  path: '/admin/orgs',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedOrgsOrgSlugStaffIndexRoute =
  ProtectedOrgsOrgSlugStaffIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrgsOrgSlugStaffRoute,
  } as any)
const ProtectedOrgsOrgSlugSchedulesIndexRoute =
  ProtectedOrgsOrgSlugSchedulesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrgsOrgSlugSchedulesRoute,
  } as any)
const ProtectedOrgsOrgSlugQualificationsIndexRoute =
  ProtectedOrgsOrgSlugQualificationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrgsOrgSlugQualificationsRoute,
  } as any)
const ProtectedOrgsOrgSlugPlatoonsIndexRoute =
  ProtectedOrgsOrgSlugPlatoonsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrgsOrgSlugPlatoonsRoute,
  } as any)
const ProtectedOrgsOrgSlugStaffAuditRoute =
  ProtectedOrgsOrgSlugStaffAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => ProtectedOrgsOrgSlugStaffRoute,
  } as any)
const ProtectedOrgsOrgSlugStaffStaffMemberIdRoute =
  ProtectedOrgsOrgSlugStaffStaffMemberIdRouteImport.update({
    id: '/$staffMemberId',
    path: '/$staffMemberId',
    getParentRoute: () => ProtectedOrgsOrgSlugStaffRoute,
  } as any)
const ProtectedOrgsOrgSlugSchedulesScheduleIdRoute =
  ProtectedOrgsOrgSlugSchedulesScheduleIdRouteImport.update({
    id: '/$scheduleId',
    path: '/$scheduleId',
    getParentRoute: () => ProtectedOrgsOrgSlugSchedulesRoute,
  } as any)
const ProtectedOrgsOrgSlugPlatoonsPlatoonIdRoute =
  ProtectedOrgsOrgSlugPlatoonsPlatoonIdRouteImport.update({
    id: '/$platoonId',
    path: '/$platoonId',
    getParentRoute: () => ProtectedOrgsOrgSlugPlatoonsRoute,
  } as any)
const ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRoute =
  ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRouteImport.update({
    id: '/positions/$positionId',
    path: '/positions/$positionId',
    getParentRoute: () => ProtectedOrgsOrgSlugQualificationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/create-org': typeof ProtectedCreateOrgRoute
  '/home': typeof ProtectedHomeRoute
  '/profile': typeof ProtectedProfileRoute
  '/join/$token': typeof JoinTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/admin': typeof ProtectedAdminAdminRoute
  '/orgs/$orgSlug': typeof ProtectedOrgsOrgSlugRouteWithChildren
  '/orgs/': typeof ProtectedOrgsIndexRoute
  '/admin/orgs': typeof ProtectedAdminAdminOrgsRoute
  '/admin/users': typeof ProtectedAdminAdminUsersRoute
  '/orgs/$orgSlug/availability': typeof ProtectedOrgsOrgSlugAvailabilityRoute
  '/orgs/$orgSlug/members': typeof ProtectedOrgsOrgSlugMembersRoute
  '/orgs/$orgSlug/platoons': typeof ProtectedOrgsOrgSlugPlatoonsRouteWithChildren
  '/orgs/$orgSlug/qualifications': typeof ProtectedOrgsOrgSlugQualificationsRouteWithChildren
  '/orgs/$orgSlug/schedules': typeof ProtectedOrgsOrgSlugSchedulesRouteWithChildren
  '/orgs/$orgSlug/staff': typeof ProtectedOrgsOrgSlugStaffRouteWithChildren
  '/orgs/$orgSlug/': typeof ProtectedOrgsOrgSlugIndexRoute
  '/orgs/$orgSlug/platoons/$platoonId': typeof ProtectedOrgsOrgSlugPlatoonsPlatoonIdRoute
  '/orgs/$orgSlug/schedules/$scheduleId': typeof ProtectedOrgsOrgSlugSchedulesScheduleIdRoute
  '/orgs/$orgSlug/staff/$staffMemberId': typeof ProtectedOrgsOrgSlugStaffStaffMemberIdRoute
  '/orgs/$orgSlug/staff/audit': typeof ProtectedOrgsOrgSlugStaffAuditRoute
  '/orgs/$orgSlug/platoons/': typeof ProtectedOrgsOrgSlugPlatoonsIndexRoute
  '/orgs/$orgSlug/qualifications/': typeof ProtectedOrgsOrgSlugQualificationsIndexRoute
  '/orgs/$orgSlug/schedules/': typeof ProtectedOrgsOrgSlugSchedulesIndexRoute
  '/orgs/$orgSlug/staff/': typeof ProtectedOrgsOrgSlugStaffIndexRoute
  '/orgs/$orgSlug/qualifications/positions/$positionId': typeof ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/create-org': typeof ProtectedCreateOrgRoute
  '/home': typeof ProtectedHomeRoute
  '/profile': typeof ProtectedProfileRoute
  '/join/$token': typeof JoinTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/admin': typeof ProtectedAdminAdminRoute
  '/orgs': typeof ProtectedOrgsIndexRoute
  '/admin/orgs': typeof ProtectedAdminAdminOrgsRoute
  '/admin/users': typeof ProtectedAdminAdminUsersRoute
  '/orgs/$orgSlug/availability': typeof ProtectedOrgsOrgSlugAvailabilityRoute
  '/orgs/$orgSlug/members': typeof ProtectedOrgsOrgSlugMembersRoute
  '/orgs/$orgSlug': typeof ProtectedOrgsOrgSlugIndexRoute
  '/orgs/$orgSlug/platoons/$platoonId': typeof ProtectedOrgsOrgSlugPlatoonsPlatoonIdRoute
  '/orgs/$orgSlug/schedules/$scheduleId': typeof ProtectedOrgsOrgSlugSchedulesScheduleIdRoute
  '/orgs/$orgSlug/staff/$staffMemberId': typeof ProtectedOrgsOrgSlugStaffStaffMemberIdRoute
  '/orgs/$orgSlug/staff/audit': typeof ProtectedOrgsOrgSlugStaffAuditRoute
  '/orgs/$orgSlug/platoons': typeof ProtectedOrgsOrgSlugPlatoonsIndexRoute
  '/orgs/$orgSlug/qualifications': typeof ProtectedOrgsOrgSlugQualificationsIndexRoute
  '/orgs/$orgSlug/schedules': typeof ProtectedOrgsOrgSlugSchedulesIndexRoute
  '/orgs/$orgSlug/staff': typeof ProtectedOrgsOrgSlugStaffIndexRoute
  '/orgs/$orgSlug/qualifications/positions/$positionId': typeof ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_protected/_admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/create-org': typeof ProtectedCreateOrgRoute
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/join/$token': typeof JoinTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/_protected/_admin/admin': typeof ProtectedAdminAdminRoute
  '/_protected/orgs/$orgSlug': typeof ProtectedOrgsOrgSlugRouteWithChildren
  '/_protected/orgs/': typeof ProtectedOrgsIndexRoute
  '/_protected/_admin/admin_/orgs': typeof ProtectedAdminAdminOrgsRoute
  '/_protected/_admin/admin_/users': typeof ProtectedAdminAdminUsersRoute
  '/_protected/orgs/$orgSlug/availability': typeof ProtectedOrgsOrgSlugAvailabilityRoute
  '/_protected/orgs/$orgSlug/members': typeof ProtectedOrgsOrgSlugMembersRoute
  '/_protected/orgs/$orgSlug/platoons': typeof ProtectedOrgsOrgSlugPlatoonsRouteWithChildren
  '/_protected/orgs/$orgSlug/qualifications': typeof ProtectedOrgsOrgSlugQualificationsRouteWithChildren
  '/_protected/orgs/$orgSlug/schedules': typeof ProtectedOrgsOrgSlugSchedulesRouteWithChildren
  '/_protected/orgs/$orgSlug/staff': typeof ProtectedOrgsOrgSlugStaffRouteWithChildren
  '/_protected/orgs/$orgSlug/': typeof ProtectedOrgsOrgSlugIndexRoute
  '/_protected/orgs/$orgSlug/platoons/$platoonId': typeof ProtectedOrgsOrgSlugPlatoonsPlatoonIdRoute
  '/_protected/orgs/$orgSlug/schedules/$scheduleId': typeof ProtectedOrgsOrgSlugSchedulesScheduleIdRoute
  '/_protected/orgs/$orgSlug/staff/$staffMemberId': typeof ProtectedOrgsOrgSlugStaffStaffMemberIdRoute
  '/_protected/orgs/$orgSlug/staff/audit': typeof ProtectedOrgsOrgSlugStaffAuditRoute
  '/_protected/orgs/$orgSlug/platoons/': typeof ProtectedOrgsOrgSlugPlatoonsIndexRoute
  '/_protected/orgs/$orgSlug/qualifications/': typeof ProtectedOrgsOrgSlugQualificationsIndexRoute
  '/_protected/orgs/$orgSlug/schedules/': typeof ProtectedOrgsOrgSlugSchedulesIndexRoute
  '/_protected/orgs/$orgSlug/staff/': typeof ProtectedOrgsOrgSlugStaffIndexRoute
  '/_protected/orgs/$orgSlug/qualifications/positions/$positionId': typeof ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/create-org'
    | '/home'
    | '/profile'
    | '/join/$token'
    | '/reset-password/$token'
    | '/verify-email/$token'
    | '/admin'
    | '/orgs/$orgSlug'
    | '/orgs/'
    | '/admin/orgs'
    | '/admin/users'
    | '/orgs/$orgSlug/availability'
    | '/orgs/$orgSlug/members'
    | '/orgs/$orgSlug/platoons'
    | '/orgs/$orgSlug/qualifications'
    | '/orgs/$orgSlug/schedules'
    | '/orgs/$orgSlug/staff'
    | '/orgs/$orgSlug/'
    | '/orgs/$orgSlug/platoons/$platoonId'
    | '/orgs/$orgSlug/schedules/$scheduleId'
    | '/orgs/$orgSlug/staff/$staffMemberId'
    | '/orgs/$orgSlug/staff/audit'
    | '/orgs/$orgSlug/platoons/'
    | '/orgs/$orgSlug/qualifications/'
    | '/orgs/$orgSlug/schedules/'
    | '/orgs/$orgSlug/staff/'
    | '/orgs/$orgSlug/qualifications/positions/$positionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/create-org'
    | '/home'
    | '/profile'
    | '/join/$token'
    | '/reset-password/$token'
    | '/verify-email/$token'
    | '/admin'
    | '/orgs'
    | '/admin/orgs'
    | '/admin/users'
    | '/orgs/$orgSlug/availability'
    | '/orgs/$orgSlug/members'
    | '/orgs/$orgSlug'
    | '/orgs/$orgSlug/platoons/$platoonId'
    | '/orgs/$orgSlug/schedules/$scheduleId'
    | '/orgs/$orgSlug/staff/$staffMemberId'
    | '/orgs/$orgSlug/staff/audit'
    | '/orgs/$orgSlug/platoons'
    | '/orgs/$orgSlug/qualifications'
    | '/orgs/$orgSlug/schedules'
    | '/orgs/$orgSlug/staff'
    | '/orgs/$orgSlug/qualifications/positions/$positionId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_protected/_admin'
    | '/_protected/create-org'
    | '/_protected/home'
    | '/_protected/profile'
    | '/join/$token'
    | '/reset-password/$token'
    | '/verify-email/$token'
    | '/_protected/_admin/admin'
    | '/_protected/orgs/$orgSlug'
    | '/_protected/orgs/'
    | '/_protected/_admin/admin_/orgs'
    | '/_protected/_admin/admin_/users'
    | '/_protected/orgs/$orgSlug/availability'
    | '/_protected/orgs/$orgSlug/members'
    | '/_protected/orgs/$orgSlug/platoons'
    | '/_protected/orgs/$orgSlug/qualifications'
    | '/_protected/orgs/$orgSlug/schedules'
    | '/_protected/orgs/$orgSlug/staff'
    | '/_protected/orgs/$orgSlug/'
    | '/_protected/orgs/$orgSlug/platoons/$platoonId'
    | '/_protected/orgs/$orgSlug/schedules/$scheduleId'
    | '/_protected/orgs/$orgSlug/staff/$staffMemberId'
    | '/_protected/orgs/$orgSlug/staff/audit'
    | '/_protected/orgs/$orgSlug/platoons/'
    | '/_protected/orgs/$orgSlug/qualifications/'
    | '/_protected/orgs/$orgSlug/schedules/'
    | '/_protected/orgs/$orgSlug/staff/'
    | '/_protected/orgs/$orgSlug/qualifications/positions/$positionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  VerifyEmailTokenRoute: typeof VerifyEmailTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/$token': {
      id: '/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof VerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/create-org': {
      id: '/_protected/create-org'
      path: '/create-org'
      fullPath: '/create-org'
      preLoaderRoute: typeof ProtectedCreateOrgRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_admin': {
      id: '/_protected/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/orgs/': {
      id: '/_protected/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof ProtectedOrgsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/orgs/$orgSlug': {
      id: '/_protected/orgs/$orgSlug'
      path: '/orgs/$orgSlug'
      fullPath: '/orgs/$orgSlug'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_admin/admin': {
      id: '/_protected/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminAdminRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/orgs/$orgSlug/': {
      id: '/_protected/orgs/$orgSlug/'
      path: '/'
      fullPath: '/orgs/$orgSlug/'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugIndexRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/orgs/$orgSlug/staff': {
      id: '/_protected/orgs/$orgSlug/staff'
      path: '/staff'
      fullPath: '/orgs/$orgSlug/staff'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugStaffRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/orgs/$orgSlug/schedules': {
      id: '/_protected/orgs/$orgSlug/schedules'
      path: '/schedules'
      fullPath: '/orgs/$orgSlug/schedules'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugSchedulesRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/orgs/$orgSlug/qualifications': {
      id: '/_protected/orgs/$orgSlug/qualifications'
      path: '/qualifications'
      fullPath: '/orgs/$orgSlug/qualifications'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugQualificationsRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/orgs/$orgSlug/platoons': {
      id: '/_protected/orgs/$orgSlug/platoons'
      path: '/platoons'
      fullPath: '/orgs/$orgSlug/platoons'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugPlatoonsRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/orgs/$orgSlug/members': {
      id: '/_protected/orgs/$orgSlug/members'
      path: '/members'
      fullPath: '/orgs/$orgSlug/members'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugMembersRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/orgs/$orgSlug/availability': {
      id: '/_protected/orgs/$orgSlug/availability'
      path: '/availability'
      fullPath: '/orgs/$orgSlug/availability'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugAvailabilityRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugRoute
    }
    '/_protected/_admin/admin_/users': {
      id: '/_protected/_admin/admin_/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof ProtectedAdminAdminUsersRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_admin/admin_/orgs': {
      id: '/_protected/_admin/admin_/orgs'
      path: '/admin/orgs'
      fullPath: '/admin/orgs'
      preLoaderRoute: typeof ProtectedAdminAdminOrgsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/orgs/$orgSlug/staff/': {
      id: '/_protected/orgs/$orgSlug/staff/'
      path: '/'
      fullPath: '/orgs/$orgSlug/staff/'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugStaffIndexRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugStaffRoute
    }
    '/_protected/orgs/$orgSlug/schedules/': {
      id: '/_protected/orgs/$orgSlug/schedules/'
      path: '/'
      fullPath: '/orgs/$orgSlug/schedules/'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugSchedulesIndexRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugSchedulesRoute
    }
    '/_protected/orgs/$orgSlug/qualifications/': {
      id: '/_protected/orgs/$orgSlug/qualifications/'
      path: '/'
      fullPath: '/orgs/$orgSlug/qualifications/'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugQualificationsIndexRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugQualificationsRoute
    }
    '/_protected/orgs/$orgSlug/platoons/': {
      id: '/_protected/orgs/$orgSlug/platoons/'
      path: '/'
      fullPath: '/orgs/$orgSlug/platoons/'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugPlatoonsIndexRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugPlatoonsRoute
    }
    '/_protected/orgs/$orgSlug/staff/audit': {
      id: '/_protected/orgs/$orgSlug/staff/audit'
      path: '/audit'
      fullPath: '/orgs/$orgSlug/staff/audit'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugStaffAuditRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugStaffRoute
    }
    '/_protected/orgs/$orgSlug/staff/$staffMemberId': {
      id: '/_protected/orgs/$orgSlug/staff/$staffMemberId'
      path: '/$staffMemberId'
      fullPath: '/orgs/$orgSlug/staff/$staffMemberId'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugStaffStaffMemberIdRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugStaffRoute
    }
    '/_protected/orgs/$orgSlug/schedules/$scheduleId': {
      id: '/_protected/orgs/$orgSlug/schedules/$scheduleId'
      path: '/$scheduleId'
      fullPath: '/orgs/$orgSlug/schedules/$scheduleId'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugSchedulesScheduleIdRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugSchedulesRoute
    }
    '/_protected/orgs/$orgSlug/platoons/$platoonId': {
      id: '/_protected/orgs/$orgSlug/platoons/$platoonId'
      path: '/$platoonId'
      fullPath: '/orgs/$orgSlug/platoons/$platoonId'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugPlatoonsPlatoonIdRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugPlatoonsRoute
    }
    '/_protected/orgs/$orgSlug/qualifications/positions/$positionId': {
      id: '/_protected/orgs/$orgSlug/qualifications/positions/$positionId'
      path: '/positions/$positionId'
      fullPath: '/orgs/$orgSlug/qualifications/positions/$positionId'
      preLoaderRoute: typeof ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRouteImport
      parentRoute: typeof ProtectedOrgsOrgSlugQualificationsRoute
    }
  }
}

interface ProtectedAdminRouteChildren {
  ProtectedAdminAdminRoute: typeof ProtectedAdminAdminRoute
  ProtectedAdminAdminOrgsRoute: typeof ProtectedAdminAdminOrgsRoute
  ProtectedAdminAdminUsersRoute: typeof ProtectedAdminAdminUsersRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminAdminRoute: ProtectedAdminAdminRoute,
  ProtectedAdminAdminOrgsRoute: ProtectedAdminAdminOrgsRoute,
  ProtectedAdminAdminUsersRoute: ProtectedAdminAdminUsersRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedOrgsOrgSlugPlatoonsRouteChildren {
  ProtectedOrgsOrgSlugPlatoonsPlatoonIdRoute: typeof ProtectedOrgsOrgSlugPlatoonsPlatoonIdRoute
  ProtectedOrgsOrgSlugPlatoonsIndexRoute: typeof ProtectedOrgsOrgSlugPlatoonsIndexRoute
}

const ProtectedOrgsOrgSlugPlatoonsRouteChildren: ProtectedOrgsOrgSlugPlatoonsRouteChildren =
  {
    ProtectedOrgsOrgSlugPlatoonsPlatoonIdRoute:
      ProtectedOrgsOrgSlugPlatoonsPlatoonIdRoute,
    ProtectedOrgsOrgSlugPlatoonsIndexRoute:
      ProtectedOrgsOrgSlugPlatoonsIndexRoute,
  }

const ProtectedOrgsOrgSlugPlatoonsRouteWithChildren =
  ProtectedOrgsOrgSlugPlatoonsRoute._addFileChildren(
    ProtectedOrgsOrgSlugPlatoonsRouteChildren,
  )

interface ProtectedOrgsOrgSlugQualificationsRouteChildren {
  ProtectedOrgsOrgSlugQualificationsIndexRoute: typeof ProtectedOrgsOrgSlugQualificationsIndexRoute
  ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRoute: typeof ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRoute
}

const ProtectedOrgsOrgSlugQualificationsRouteChildren: ProtectedOrgsOrgSlugQualificationsRouteChildren =
  {
    ProtectedOrgsOrgSlugQualificationsIndexRoute:
      ProtectedOrgsOrgSlugQualificationsIndexRoute,
    ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRoute:
      ProtectedOrgsOrgSlugQualificationsPositionsPositionIdRoute,
  }

const ProtectedOrgsOrgSlugQualificationsRouteWithChildren =
  ProtectedOrgsOrgSlugQualificationsRoute._addFileChildren(
    ProtectedOrgsOrgSlugQualificationsRouteChildren,
  )

interface ProtectedOrgsOrgSlugSchedulesRouteChildren {
  ProtectedOrgsOrgSlugSchedulesScheduleIdRoute: typeof ProtectedOrgsOrgSlugSchedulesScheduleIdRoute
  ProtectedOrgsOrgSlugSchedulesIndexRoute: typeof ProtectedOrgsOrgSlugSchedulesIndexRoute
}

const ProtectedOrgsOrgSlugSchedulesRouteChildren: ProtectedOrgsOrgSlugSchedulesRouteChildren =
  {
    ProtectedOrgsOrgSlugSchedulesScheduleIdRoute:
      ProtectedOrgsOrgSlugSchedulesScheduleIdRoute,
    ProtectedOrgsOrgSlugSchedulesIndexRoute:
      ProtectedOrgsOrgSlugSchedulesIndexRoute,
  }

const ProtectedOrgsOrgSlugSchedulesRouteWithChildren =
  ProtectedOrgsOrgSlugSchedulesRoute._addFileChildren(
    ProtectedOrgsOrgSlugSchedulesRouteChildren,
  )

interface ProtectedOrgsOrgSlugStaffRouteChildren {
  ProtectedOrgsOrgSlugStaffStaffMemberIdRoute: typeof ProtectedOrgsOrgSlugStaffStaffMemberIdRoute
  ProtectedOrgsOrgSlugStaffAuditRoute: typeof ProtectedOrgsOrgSlugStaffAuditRoute
  ProtectedOrgsOrgSlugStaffIndexRoute: typeof ProtectedOrgsOrgSlugStaffIndexRoute
}

const ProtectedOrgsOrgSlugStaffRouteChildren: ProtectedOrgsOrgSlugStaffRouteChildren =
  {
    ProtectedOrgsOrgSlugStaffStaffMemberIdRoute:
      ProtectedOrgsOrgSlugStaffStaffMemberIdRoute,
    ProtectedOrgsOrgSlugStaffAuditRoute: ProtectedOrgsOrgSlugStaffAuditRoute,
    ProtectedOrgsOrgSlugStaffIndexRoute: ProtectedOrgsOrgSlugStaffIndexRoute,
  }

const ProtectedOrgsOrgSlugStaffRouteWithChildren =
  ProtectedOrgsOrgSlugStaffRoute._addFileChildren(
    ProtectedOrgsOrgSlugStaffRouteChildren,
  )

interface ProtectedOrgsOrgSlugRouteChildren {
  ProtectedOrgsOrgSlugAvailabilityRoute: typeof ProtectedOrgsOrgSlugAvailabilityRoute
  ProtectedOrgsOrgSlugMembersRoute: typeof ProtectedOrgsOrgSlugMembersRoute
  ProtectedOrgsOrgSlugPlatoonsRoute: typeof ProtectedOrgsOrgSlugPlatoonsRouteWithChildren
  ProtectedOrgsOrgSlugQualificationsRoute: typeof ProtectedOrgsOrgSlugQualificationsRouteWithChildren
  ProtectedOrgsOrgSlugSchedulesRoute: typeof ProtectedOrgsOrgSlugSchedulesRouteWithChildren
  ProtectedOrgsOrgSlugStaffRoute: typeof ProtectedOrgsOrgSlugStaffRouteWithChildren
  ProtectedOrgsOrgSlugIndexRoute: typeof ProtectedOrgsOrgSlugIndexRoute
}

const ProtectedOrgsOrgSlugRouteChildren: ProtectedOrgsOrgSlugRouteChildren = {
  ProtectedOrgsOrgSlugAvailabilityRoute: ProtectedOrgsOrgSlugAvailabilityRoute,
  ProtectedOrgsOrgSlugMembersRoute: ProtectedOrgsOrgSlugMembersRoute,
  ProtectedOrgsOrgSlugPlatoonsRoute:
    ProtectedOrgsOrgSlugPlatoonsRouteWithChildren,
  ProtectedOrgsOrgSlugQualificationsRoute:
    ProtectedOrgsOrgSlugQualificationsRouteWithChildren,
  ProtectedOrgsOrgSlugSchedulesRoute:
    ProtectedOrgsOrgSlugSchedulesRouteWithChildren,
  ProtectedOrgsOrgSlugStaffRoute: ProtectedOrgsOrgSlugStaffRouteWithChildren,
  ProtectedOrgsOrgSlugIndexRoute: ProtectedOrgsOrgSlugIndexRoute,
}

const ProtectedOrgsOrgSlugRouteWithChildren =
  ProtectedOrgsOrgSlugRoute._addFileChildren(ProtectedOrgsOrgSlugRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedCreateOrgRoute: typeof ProtectedCreateOrgRoute
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedOrgsOrgSlugRoute: typeof ProtectedOrgsOrgSlugRouteWithChildren
  ProtectedOrgsIndexRoute: typeof ProtectedOrgsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedCreateOrgRoute: ProtectedCreateOrgRoute,
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedOrgsOrgSlugRoute: ProtectedOrgsOrgSlugRouteWithChildren,
  ProtectedOrgsIndexRoute: ProtectedOrgsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  JoinTokenRoute: JoinTokenRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  VerifyEmailTokenRoute: VerifyEmailTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
